<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
        <Authors>Metarract</Authors>
        <Description>A collection of state-based models</Description>
        <RepositoryUrl>https://github.com/Metarract/StateLib</RepositoryUrl>
        <PackageId>Metarract.StateLib</PackageId>
        <Version>0.1.0</Version>
    </PropertyGroup>
    <ItemGroup>
      <None Include=".gitignore" />
      <None Include="pushLocalPackage.ps1" />
    </ItemGroup>
    <ItemGroup>
      <Content Include="LICENSE" />
      <Content Include="README.md" />
    </ItemGroup>
</Project>
